---
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False 
  become: False

  tasks:

  - name: Create a security group
    ec2_group:
      name: contrail
      description: "Contrail Security Group"
      region: "{{ aws_region }}"
      vpc_id: "{{ vpc_id }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      rules:
        - proto: all
          cidr_ip: 0.0.0.0/0
        - proto: all
          group_name: openshift-contrail
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: firewall

  - name: Create Master/Node EC2 instances
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      key_name: "{{ key_name }}"
      region: "{{ aws_region }}"
      group_id: "{{ firewall.group_id }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      assign_public_ip: yes
      user_data: "{{ lookup('file', 'cloud-init/init.sh') }}"
      wait: yes
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 200
          delete_on_termination: true
      exact_count: "{{ count }}"
      count_tag:
         Name: "{{ ec2_tag }}"
      instance_tags:
         Name: "{{ ec2_tag }}"
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
