apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    tier: db
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "demo", "name":"database-net"}'
  }
spec:
  containers:
    - name: db-pod
      image: mysql
      env:
        - name: MYSQL_DATABASE
          value: redmine
        - name: MYSQL_ROOT_PASSWORD
          value: secret
