apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    tier: web
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "demo", "name":"frontend-network"}'
  }
spec:
  containers:
    - name: frontend-pod
      image: savvythru/web-app-qa
      ports:
      - containerPort: 80
