apiVersion: v1
kind: Pod
metadata:
  name: custom-app
  labels:
    app: custom-app
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "admin", "name":"public"}'
  }
spec:
  containers:
    - name: custom-app
      image: ubuntu-upstart
