heat_template_version: 2014-10-16

description: Create a server instance & fetch MAC & port UUID

parameters:

  server_left_name:
    type: string
  server_right_name:
    type: string
  image:
    type: string
  flavor:
    type: string
  private_net_name_0: 
    type: string
  private_net_cidr_0:
    type: string
  private_net_gateway_0:
    type: string

resources:
  private_net_0:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_net_name_0 }

  private_subnet_0:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net_0 }
      cidr: { get_param: private_net_cidr_0 }
      gateway_ip: { get_param: private_net_gateway_0 }

  server_1:
    type: OS::Nova::Server
    properties:
      name: { get_param: server_left_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: { get_resource: private_net_0 }

outputs:
  server_1_mac:
    description: Server Stats
    value: { get_attr: [server_1, addresses, get_param: private_net_name_0, 0, "OS-EXT-IPS-MAC:mac_addr"] }
  server_1_port_uuid:
    description: Port UUID
    value: { get_attr: [server_1, addresses, get_param: private_net_name_0, 0, "port"] }
