apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    tier: web
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "demo", "name":"frontend-net"}'
  }
spec:
  containers:
    - name: web-pod
      image: redmine
      env:
        - name: REDMINE_DB_MYSQL
          value: <mysql-pod/svc-IP>
        - name: REDMINE_DB_PASSWORD
          value: secret
