analyticsdb_min_diskgb: 50
configdb_min_diskgb: 25
aaa_mode: no-auth
auth_mode: noaut
cloud_orchestrator: kubernetes
log_level: SYS_NOTICE
metadata_proxy_secret: contrail
rabbitmq_node_port: 5672
zookeeper_analytics_port: 2182
zookeeper_port: 2181
zookeeper_ports: 2888:3888
zookeeper_analytics_ports: 4888:5888
vrouter_physical_interface: eth0
kubernetes_api_secure_port: 6443
contrail_registry: hub.juniper.net/contrail
